ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

UPDATE "user" SET status = 'ACTIVE'
WHERE status IS NULL OR status = '';

CREATE INDEX IF NOT EXISTS idx_user_status ON "user"(status);

ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS vto_usage INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS vto_reset_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
