ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS reminder_1d_sent BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS reminder_3h_sent BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS payment_proof_sent BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS payment_proof_url VARCHAR(255);
