/**
 * Migration: Configure auto-increment sequence identity for opening_time.id.
 * @param {import('pg').PoolClient} client 
 */
export async function migrate(client) {
    const checkIdentity = await client.query(`
        SELECT column_name, is_identity 
        FROM information_schema.columns 
        WHERE table_name = 'opening_time' AND column_name = 'id'
    `);
    if (checkIdentity.rows.length > 0 && checkIdentity.rows[0].is_identity !== 'YES') {
        await client.query(`
            ALTER TABLE opening_time 
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
        `);
        await client.query(`
            SELECT setval(
                pg_get_serial_sequence('opening_time', 'id'), 
                COALESCE((SELECT MAX(id) FROM opening_time), 1)
            )
        `);
        console.log('[Migration] opening_time.id auto-increment sequence configured.');
    }
}
